menu:
  Home:
  About: about
  Archives: archives


widgets:
- search
- category
- tag

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: false
  pinterest: false

fancybox: false

google_analytics:
rss:
